base_url = "https://thisisnorthkitsap.com"

title = "This Is North Kitsap"
description = "My photoblog from places close to home."
default_language = "en"

theme = "zola-es-theme"

compile_sass = true
build_search_index = true

generate_feeds = true
feed_filenames = ["rss.xml"]

[search]
index_format = "elasticlunr_json"

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
endmark = true
map_clustering = false
is_dark = true
es_site = "thisisnorthkitsap"
article_type = "Kitsap photo stories"
fathom_site_id = "NLYTYGEA"
section_reverse_default = true
comments_enabled_default = false
